//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.17 at 10:00:04 AM MAGT 
//


package org.dbpedia.lookup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.dbpedia.lookup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.dbpedia.lookup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfResult }
     * 
     */
    public ArrayOfResult createArrayOfResult() {
        return new ArrayOfResult();
    }

    /**
     * Create an instance of {@link ArrayOfResult.Result }
     * 
     */
    public ArrayOfResult.Result createArrayOfResultResult() {
        return new ArrayOfResult.Result();
    }

    /**
     * Create an instance of {@link ArrayOfResult.Result.Categories }
     * 
     */
    public ArrayOfResult.Result.Categories createArrayOfResultResultCategories() {
        return new ArrayOfResult.Result.Categories();
    }

    /**
     * Create an instance of {@link ArrayOfResult.Result.Classes }
     * 
     */
    public ArrayOfResult.Result.Classes createArrayOfResultResultClasses() {
        return new ArrayOfResult.Result.Classes();
    }

    /**
     * Create an instance of {@link ArrayOfResult.Result.Categories.Category }
     * 
     */
    public ArrayOfResult.Result.Categories.Category createArrayOfResultResultCategoriesCategory() {
        return new ArrayOfResult.Result.Categories.Category();
    }

    /**
     * Create an instance of {@link ArrayOfResult.Result.Classes.Class }
     * 
     */
    public ArrayOfResult.Result.Classes.Class createArrayOfResultResultClassesClass() {
        return new ArrayOfResult.Result.Classes.Class();
    }

}
